### ISSUE TITLE
Error TS2304: Cannot find name 'https'

### ISSUE THREAD

**Issue by websharik** [mtasa-typescript/resource-boilerplate#31]
`node_modules/mtasa-lua-types/types/mtasa/client/function/event.d.ts:114:25 - error TS2304: Cannot find name 'https'.

114 export declare function addEventHandler(
                            ~~~~~~~~~~~~~~~

node_modules/mtasa-lua-types/types/mtasa/client/function/output.d.ts:87:25 - error TS2304: Cannot find name 'https'.

87 export declare function outputChatBox(
                           ~~~~~~~~~~~~~

node_modules/mtasa-lua-types/types/mtasa/client/function/utility.d.ts:1148:25 - error TS2304: Cannot find name 'https'.

1148 export declare function setTimer(
                             ~~~~~~~~

node_modules/mtasa-lua-types/types/mtasa/client/function/world.d.ts:407:25 - error TS2304: Cannot find name 'https'.

407 export declare function getTime(): LuaMultiReturn<[
                            ~~~~~~~

node_modules/mtasa-lua-types/types/mtasa/server/function/event.d.ts:97:25 - error TS2304: Cannot find name 'https'.

97 export declare function addEventHandler(
                           ~~~~~~~~~~~~~~~

node_modules/mtasa-lua-types/types/mtasa/server/function/output.d.ts:67:25 - error TS2304: Cannot find name 'https'.

67 export declare function outputChatBox(
                           ~~~~~~~~~~~~~

Found 6 errors. Watching for file changes.
`

Resolve: add `declare var https: any` to types/additional.d.ts

**Comment by Toliak** [comment]
Thank you for issue! 
I'm working on fixing this problem
I believe, I will finish this evening

The origin of the bug is described here: https://github.com/TypeScriptToLua/TypeScriptToLua/issues/1058

**Comment by Toliak** [comment]
@websharik , I have patched `@see` comment generation, therefore, the error has been fixed.
You can comment below or reopen this issue, if the problem is still reproducible.
