### ISSUE TITLE
Discord Server for quick support

### ISSUE THREAD

**Issue by MAmmar-DEV** [mtasa-typescript/resource-boilerplate#50]
Hy, I am actually interested in you project and have learned Typescript for scripting MTA:SA server. 

Well there are many small problems and guides I need from you. So for small problems and guide, it would be not good to create issues for small problems. So I suggested to please make a discord server for quick support. 

If you dont mind contact me on discord Vizzy#4868 , and allow me to create a discord server ,will make you owner and I will be as a Moderator 

Thanks.

**Comment by Toliak** [comment]
Ok, I will create the Discord server and put the link here

**Comment by Toliak** [comment]
I have created the discord channel
https://discord.gg/67vxSwhRT4
